version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    ports:
      - "9200:9200"
#      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/khemtz/elastic/docker/elasticsearch/data:/usr/share/elasticsearch/data:rw
      #- /home/devops/docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment: 
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=uao_test
      - discovery.type=single-node
      #- bootstrap.memory_lock=true
      - xpack.security.enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    #volumes:
    #  - /home/devops/docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
     - SERVERNAME=kibana
     - ELASTICSEARCH_HOSTS=http://192.168.100.9:9200
    restart: always
    ports:
      - "5601:5601"